server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8

jwt:
  secret: "asdfasdfasdfasdfasdfasdfasdfasdfasdfasdf" # 256 bytes or more
  token:
    access-expires: 600000 # 1000 * 60 (1min)
    refresh-expires: 86400000